package com.groupeisi;

import com.groupeisi.entity.Etudiant;
import jakarta.annotation.Generated;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Generated(value = "JHipster", comments = "Generated by JHipster 8.1.0")
@Retention(RetentionPolicy.SOURCE)
@Target({ ElementType.TYPE })
public @interface GeneratedByJHipster {
    interface EtudiantService {
        Etudiant creer(Etudiant etudiant);
        Iterable<Etudiant> lire();
        Etudiant modifier(int id, Etudiant etudiant);
        String supprimer(int id);
    }
}
